version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    ports:
      - "5431:8080"
      - "5432:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Todos;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;

  migration:
    image: ${DOCKER_REGISTRY-}migration
    build:
      context: .
      dockerfile: MigrationService/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Todos;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

